version: "3.8"

networks:
    portfolio:
        name: portfolio

services:
    website:
        image: ghcr.io/leo-saldanha/pkmn-help-with-test-ids:master
        ports:
            - "5173:5173"
        networks: [portfolio]
