version: "3.8"

networks:
    portfolio:
        name: portfolio
        external: true

services:
    test-runner:
        build: 
            context: .
            dockerfile: ./selenium.Dockerfile
        networks: [portfolio]
        command: >
            sh -c "
                ls -la &&
                pwd &&
                tox -e selenium -- --env=docker --headless"