name: run-cypress
run-name: Run Cypress tests

on:
  schedule:
    - cron: "0 9 * * *"
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: leo-saldanha/pkmn-help-with-test-ids
          token: ${{ secrets.GH_PAT }}

      # - name: Build and launch
      #   run: docker-compose up -d

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: pkmn-help-with-test-ids:latest
          outputs: type=docker,dest=/tmp/pkmn-help-with-test-ids.tar

      - uses: actions/upload-artifact@v3
        with:
          name: pkmn-help-with-test-ids
          path: /tmp/pkmn-help-with-test-ids.tar

  run-tests:
    runs-on: ubuntu-latest
    needs: deploy-website
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v2
        with:
          name: pkmn-help-with-test-ids
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/pkmn-help-with-test-ids.tar
          docker run -d -t pkmn-help-with-test-ids:latest

      - uses: actions/checkout@v4

      - run: |
          cd javascript
          docker compose up
