name: run-cypress
run-name: Run Cypress tests

on:
  schedule:
    - cron: "0 9 * * *"
  pull_request:
    branches: [ "main" ]

jobs:
  pkmn-help:
    uses: ./.github/workflows/build-website-workflow.yml
    secrets:
      token: ${{ secrets.GH_PAT }}

  run-tests:
    runs-on: ubuntu-latest
    needs: pkmn-help
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v2
        with:
          name: pkmn-help-with-test-ids
          path: /tmp

      - run: |
          docker load --input /tmp/pkmn-help-with-test-ids.tar
          docker compose up -d

      - uses: actions/checkout@v4

      - run: docker compose -f javascript/docker-compose-cypress.yml up
