name: run-cypress
run-name: run-cypress

on:
  schedule:
    - cron: "0 9 * * *"
  pull_request:
    branches: [ "main" ]
    paths:
      - javascript/**
      - .github/workflows/**
      - test_data/**
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker compose -f docker-compose.yml up -d

      - run: docker compose -f javascript/docker-compose-cypress.yml up --build --exit-code-from=cypress-chrome
