name: run-cypress
run-name: Run Cypress tests

on:
  schedule:
    - cron: "0 9 * * *"
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-website:
    uses: ./.github/workflows/build-website-workflow.yml

  run-tests:
    runs-on: ubuntu-latest
    needs: deploy-website
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v2
        with:
          name: pkmn-help-with-test-ids
          path: /tmp

      - run: |
          docker load --input /tmp/pkmn-help-with-test-ids.tar
          docker run -d -t pkmn-help-with-test-ids:latest

      - uses: actions/checkout@v4

      - run: |
          docker ps
          docker compose -f javascript/docker-compose.yml up
