name: run-selenium
run-name: run-selenium

on:
  schedule:
    - cron: "0 9 * * *"
  pull_request:
    branches: [ "main" ]
    paths:
      - python/**
      - .github/workflows/**
      - test_data/**
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u leo-saldanha --password-stdin

      - run: docker compose -f docker-compose.yml up -d

      - run: docker compose -f python/selenium/docker-compose-selenium-grid.yml up -d --build
      - run: docker compose -f python/selenium/docker-compose-selenium-tests.yml up --build --exit-code-from=test-runner
