name: run-selenium
run-name: run-selenium

on:
  schedule:
    - cron: "0 9 * * *"
  push:
    paths:
      - python/**

jobs:
  pkmn-help:
    uses: ./.github/workflows/build-website-workflow.yml
    secrets:
      token: ${{ secrets.GH_PAT }}

  run-tests:
    runs-on: ubuntu-latest
    needs: pkmn-help
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v2
        with:
          name: pkmn-help-with-test-ids
          path: /tmp

      - uses: actions/checkout@v4

      - run: |
          docker load --input /tmp/pkmn-help-with-test-ids.tar
          docker compose -f docker-compose.yml up -d

      - run: docker compose -f python/selenium/docker-compose-selenium-grid.yml up -d --build
      - run: docker compose -f python/selenium/docker-compose-selenium.yml up --build
